name: Run Status Checks

on: pull_request

jobs:
  status-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pip install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: poetry
      - run: poetry install

      - name: Run Status Checks
        uses: devcontainers/ci@v0.3.1900000349
        with:
          runCmd: python -m status_check_runner
          # Use `inheritEnv: true` instead of explicitly setting the environment once the below
          # commit is included in a release (currently seems to be planned for v0.3.1900000350)
          # https://github.com/devcontainers/ci/commit/4dc5cb43f319c991f9531be34d682a8ffa8bfb4c
          env: GITHUB_ACTIONS=true
